### ISSUE TITLE
Dirtmouth item not shown as reachable when another stag location is reachable

### ISSUE THREAD

**Issue by zeroZshadow** [CaptainDapper/HollowKnight.RandoMapMod#3]
With Randomizer 3.0, the dirtmouth stag location can always be traveled too from any other stag, even without unlocking dirtmouth first.
This puts the item at this location in play, and is sometimes required for progression.

The map currently doesn't show the item as reachable until the stage location has been "unlocked" through the item.
An example of this would be seed `202101240` on all standard settings.

**Comment by CaptainDapper** [comment]
Fairly certain this is fixed now- Whether by rando fixing it or by the newest update.
